CATEGORIES = [
    ('ART', 'Art'),
    ('BIOG', 'Biography'),
    ('BUS', 'Business'),
    ('CHR', 'Christian'),
    ('CLA', 'Classics'),
    ('COM', 'Comics'),
    ('COOK', 'Cookbooks'),
    ('EBOOK', 'Ebooks'),
    ('FAN', 'Fantasy'),
    ('FIC', 'Fiction'),
    ('GRAPH-NOV', 'Graphic Novels'),
    ('HIST-FIC', 'Historical Fiction'),
    ('HIS', 'History'),
    ('HOR', 'Horror'),
    ('MEM', 'Memoir'),
    ('MUS', 'Music'),
    ('MYS', 'Mystery'),
    ('NF', 'Nonfiction'),
    ('POE', 'Poetry'),
    ('PSY', 'Psychology'),
    ('ROM', 'Romance'),
    ('SCI', 'Science'),
    ('SCI-FIC', 'Science Fiction'),
    ('SH', 'Self Help'),
    ('SPT', 'Sports'),
    ('THR', 'Thriller'),
    ('TRV', 'Travel'),
    ('YA', 'Young Adult'),
]