# Generated by Django 4.2.11 on 2025-03-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BooksVault", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="num_of_volumes",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
