# Generated by Django 4.2.11 on 2025-03-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BooksVault", "0002_alter_book_num_of_volumes"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[("READ", "Read"), ("UNREAD", "Unread")],
                default="UNREAD",
                max_length=6,
            ),
        ),
    ]
