# Generated by Django 4.2.11 on 2025-03-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BooksVault", "0003_book_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="Authors",
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ART", "Art"),
                    ("BIOG", "Biography"),
                    ("BUS", "Business"),
                    ("CHR", "Christian"),
                    ("CLA", "Classics"),
                    ("COM", "Comics"),
                    ("COOK", "Cookbooks"),
                    ("EBOOK", "Ebooks"),
                    ("FAN", "Fantasy"),
                    ("FIC", "Fiction"),
                    ("GRAPH-NOV", "Graphic Novels"),
                    ("HIST-FIC", "Historical Fiction"),
                    ("HIS", "History"),
                    ("HOR", "Horror"),
                    ("MEM", "Memoir"),
                    ("MUS", "Music"),
                    ("MYS", "Mystery"),
                    ("NF", "Nonfiction"),
                    ("POE", "Poetry"),
                    ("PSY", "Psychology"),
                    ("ROM", "Romance"),
                    ("SCI", "Science"),
                    ("SCI-FIC", "Science Fiction"),
                    ("SH", "Self Help"),
                    ("SPT", "Sports"),
                    ("THR", "Thriller"),
                    ("TRV", "Travel"),
                    ("YA", "Young Adult"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[("READ", "Read"), ("UNREAD", "Unread")],
                default="Unreaded",
                max_length=6,
            ),
        ),
    ]
