# Generated by Django 4.2.11 on 2025-03-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BooksVault", "0004_rename_author_authors_alter_book_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="Language",
            field=models.CharField(
                choices=[
                    ("ENG", "English"),
                    ("SPA", "Spanish"),
                    ("RUS", "Russian"),
                    ("GER", "German"),
                    ("FRE", "French"),
                    ("ITA", "Italian"),
                    ("ARA", "Arabic"),
                    ("TUR", "Turkish"),
                    ("JAP", "Japanese"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="type",
            field=models.CharField(
                choices=[("BK", "Book"), ("NOV", "Novel")], max_length=3, null=True
            ),
        ),
    ]
