# Generated by Django 4.2.11 on 2025-03-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BooksVault", "0005_book_language_book_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
