# Generated by Django 4.2.11 on 2025-03-26 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BooksVault", "0006_book_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="Language",
            new_name="language",
        ),
        migrations.RemoveField(
            model_name="book",
            name="description",
        ),
        migrations.RemoveField(
            model_name="book",
            name="status",
        ),
        migrations.AddField(
            model_name="authors",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publisher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
