# Generated by Django 5.1.7 on 2025-04-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BooksVault", "0007_rename_language_book_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="language",
        ),
        migrations.RemoveField(
            model_name="book",
            name="num_of_pages",
        ),
        migrations.RemoveField(
            model_name="book",
            name="num_of_volumes",
        ),
        migrations.RemoveField(
            model_name="book",
            name="type",
        ),
        migrations.AddField(
            model_name="book",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
