# Generated by Django 5.2 on 2025-04-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksVault', '0009_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='address',
        ),
    ]
